/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.team29.westernmap;

import java.awt.Image;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.ParseException;


/**
 *
 * @author Tristan
 */
public class GUIMap extends javax.swing.JFrame {

    /**
     * Creates new form GUIMap
     * @throws java.io.IOException
     * @throws java.lang.InterruptedException
     * @throws org.json.simple.parser.ParseException
     */
    public GUIMap() throws IOException, InterruptedException, ParseException {
        initComponents();
        FloorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ground Floor", "First Floor", "Second Floor", "Third Floor", "Fourth Floor"}));
        floormap.setIcon(new ImageIcon("src/main/java/images/western.png"));
        displayWeather();
    }

    public void displayWeather() throws IOException, InterruptedException, ParseException{
        Weather weather = new Weather();
        JSONObject info = (JSONObject) weather.getWeather();
        String location = (String) info.get("address");
        JSONArray days = (JSONArray) info.get("days");
        JSONObject days2 = (JSONObject) days.get(0);
        double tempmin = (double) days2.get("tempmin");
        String datetime = (String) days2.get("datetime");
        double feelslike = (double) days2.get("feelslike");
        double tempmax = (double) days2.get("tempmax");
        double temp = (double) days2.get("temp");
        
        loctable2.setText(location);
        datelabel.setText(datetime);
        mintemplabel.setText(tempmin + " °C");
        maxtemplabel.setText(tempmax + " °C");
        feelslabel.setText(feelslike + " °C");
        templabel.setText(temp + " °C");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buildingcombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FloorComboBox = new javax.swing.JComboBox<>();
        searchBotton = new javax.swing.JButton();
        UserHelpBotton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        templabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mintemplabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maxtemplabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        feelslabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        loctable2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        floormap = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buildingcombo.setBackground(new java.awt.Color(138, 43, 226));
        buildingcombo.setForeground(new java.awt.Color(255, 255, 255));
        buildingcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Middlesex College", "Arts and Humanities Building", "Elborn College" }));
        buildingcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingcomboActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(138, 43, 226));
        jLabel2.setForeground(new java.awt.Color(138, 43, 226));
        jLabel2.setText("Building:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        FloorComboBox.setBackground(new java.awt.Color(138, 43, 226));
        FloorComboBox.setForeground(new java.awt.Color(255, 255, 255));
        FloorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FloorComboBoxActionPerformed(evt);
            }
        });

        searchBotton.setBackground(new java.awt.Color(138, 43, 226));
        searchBotton.setForeground(new java.awt.Color(255, 255, 255));
        searchBotton.setText("Search");
        searchBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBottonActionPerformed(evt);
            }
        });

        UserHelpBotton.setBackground(new java.awt.Color(138, 43, 226));
        UserHelpBotton.setForeground(new java.awt.Color(255, 255, 255));
        UserHelpBotton.setText("UserHelp");
        UserHelpBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserHelpBottonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(138, 43, 226));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Weather:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current Temp:");

        templabel.setForeground(new java.awt.Color(255, 255, 255));
        templabel.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Min Temp:");

        mintemplabel.setForeground(new java.awt.Color(255, 255, 255));
        mintemplabel.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Max Temp");

        maxtemplabel.setForeground(new java.awt.Color(255, 255, 255));
        maxtemplabel.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Feels Like:");

        feelslabel.setForeground(new java.awt.Color(255, 255, 255));
        feelslabel.setText("jLabel10");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Location:");

        loctable2.setForeground(new java.awt.Color(255, 255, 255));
        loctable2.setText("loc");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date:");

        datelabel.setForeground(new java.awt.Color(255, 255, 255));
        datelabel.setText("date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loctable2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datelabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(templabel)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(14, 14, 14)))
                            .addComponent(mintemplabel)
                            .addComponent(maxtemplabel)
                            .addComponent(feelslabel))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(templabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mintemplabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxtemplabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feelslabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loctable2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datelabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(floormap);

        title.setBackground(new java.awt.Color(138, 43, 226));
        title.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(138, 43, 226));
        title.setText("Western Maps");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserHelpBotton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(searchBotton)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buildingcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(FloorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(533, 533, 533)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(232, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(UserHelpBotton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buildingcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addComponent(FloorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBotton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buildingcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingcomboActionPerformed
        // TODO add your handling code here:
        System.out.println(buildingcombo.getItemAt(buildingcombo.getSelectedIndex()));
        String buildingName = buildingcombo.getItemAt(buildingcombo.getSelectedIndex());
        if (buildingName.equals("Middlesex College")){
            FloorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ground Floor", "First Floor", "Second Floor", "Third Floor", "Fourth Floor" }));
        }else if(buildingName.equals("Arts and Humanities Building")){
            FloorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lower Floor", "First Floor"}));
        }else if(buildingName.equals("Elborn College")){
            FloorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Floor", "Second Floor"}));
        }
    }//GEN-LAST:event_buildingcomboActionPerformed

    private void FloorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FloorComboBoxActionPerformed
        // TODO add your handling code here:
        System.out.print(".");
    }//GEN-LAST:event_FloorComboBoxActionPerformed

    private void searchBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBottonActionPerformed
        String buildingName = buildingcombo.getItemAt(buildingcombo.getSelectedIndex());
        String floorName = FloorComboBox.getItemAt(FloorComboBox.getSelectedIndex());
        if (buildingName.equals("Middlesex College")) {
            if(floorName.equals("Ground Floor")){
                new MC_groundfloor().setVisible(true);
            }else if (floorName.equals("First Floor")){
                new MC_firstfloor().setVisible(true);
            }else if (floorName.equals("Second Floor")){
                new MC_secondfloor().setVisible(true);
            }else if (floorName.equals("Third Floor")){
                new MC_thirdfloor().setVisible(true);
            }else if (floorName.equals("Fourth Floor")){
                new MC_fourthfloor().setVisible(true);
            }
        }else if(buildingName.equals("Arts and Humanities Building")){
            if(floorName.equals("Lower Floor")){
                new AHB_lowerfloor().setVisible(true);
                
            }else if(floorName.equals("First Floor")){
                new AHB_firstfloor().setVisible(true);  
            }
        } else if(buildingName.equals("Elborn College")){
        	if (floorName.equals("First Floor")){
                    new EC_firstfloor().setVisible(true); 
            } else if (floorName.equals("Second Floor")) {
                    new EC_secondfloor().setVisible(true);
            }
        }
    }//GEN-LAST:event_searchBottonActionPerformed

    private void UserHelpBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserHelpBottonActionPerformed
        new UserHelp3().setVisible(true);
    }//GEN-LAST:event_UserHelpBottonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FloorComboBox;
    private javax.swing.JButton UserHelpBotton;
    private javax.swing.JComboBox<String> buildingcombo;
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel feelslabel;
    private javax.swing.JLabel floormap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loctable2;
    private javax.swing.JLabel maxtemplabel;
    private javax.swing.JLabel mintemplabel;
    private javax.swing.JButton searchBotton;
    private javax.swing.JLabel templabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
