/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.team29.westernmap;

import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.JSONArray;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Tristan
 */
public class UserCreate extends javax.swing.JFrame {
    private String building;
    private String floors;
    private String names;
    private String roomnumber;
    private String category;
    private String description;
    private int x;
    private int y;
    private boolean conf;
    /**
     * Creates new form UserCreate
     */
    public UserCreate(int x, int y) {
        this.x = x;
        this.y = y;
        this.conf = true;
        this.building = "Unselected";
        this.floors = "Unselected";
        initComponents();
        lower.setVisible(false);
        ground.setVisible(false);
        first.setVisible(false);
        second.setVisible(false);
        third.setVisible(false);
        fourth.setVisible(false);
        
    }
    public boolean getConf(){
        return this.conf;
    }
    public void setConf(boolean con){
        this.conf = con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rm = new javax.swing.JTextField();
        cat = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mc = new javax.swing.JButton();
        ec = new javax.swing.JButton();
        ahb = new javax.swing.JButton();
        lower = new javax.swing.JButton();
        ground = new javax.swing.JButton();
        first = new javax.swing.JButton();
        second = new javax.swing.JButton();
        third = new javax.swing.JButton();
        fourth = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Building: (MC, EC, AHB)");

        jLabel2.setText("Floor:");

        jLabel3.setText("Room Number:");

        jLabel4.setText("Category:");

        jLabel5.setText("Description:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Name:");

        mc.setText("MC");
        mc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcActionPerformed(evt);
            }
        });

        ec.setText("EC");
        ec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecActionPerformed(evt);
            }
        });

        ahb.setText("AHB");
        ahb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ahbActionPerformed(evt);
            }
        });

        lower.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lower.setText("Lower Floor");
        lower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerActionPerformed(evt);
            }
        });

        ground.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        ground.setText("Ground Floor");
        ground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groundActionPerformed(evt);
            }
        });

        first.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        first.setText("First Floor");
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });

        second.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        second.setText("Second Floor");
        second.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondActionPerformed(evt);
            }
        });

        third.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        third.setText("Third Floor");
        third.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdActionPerformed(evt);
            }
        });

        fourth.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        fourth.setText("Fourth Floor");
        fourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(293, 293, 293)
                            .addComponent(jButton2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ec)
                                        .addGap(42, 42, 42)
                                        .addComponent(ahb))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rm, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                    .addComponent(cat)))
                            .addComponent(desc)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(lower)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ground)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(first)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(second)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(third)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fourth)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mc)
                    .addComponent(ec)
                    .addComponent(ahb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lower)
                    .addComponent(ground)
                    .addComponent(first)
                    .addComponent(second)
                    .addComponent(third)
                    .addComponent(fourth))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.conf = false;
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.names = name.getText();
        this.roomnumber = rm.getText();
        this.category = cat.getText();
        this.description = desc.getText();
        String file = "src/main/java/JSONMetaData/userCreated.json";
        JSONParser parser = new JSONParser();
        try {
            Object obj = parser.parse(new FileReader(file));
            JSONObject jsonFile = (JSONObject) obj;
            JSONArray jsonType = (JSONArray) jsonFile.get("UserCreated");
            JSONObject poiDetails = (JSONObject) jsonType.get(0);
            if(poiDetails.size() == 0){
                poiDetails.put("building", this.building);
                poiDetails.put("floor", this.floors);
                poiDetails.put("name", this.names);
                poiDetails.put("roomNumber", this.roomnumber);
                poiDetails.put("category", this.category);
                poiDetails.put("description", this.description);
                poiDetails.put("highlighted", false);
                poiDetails.put("x", this.x);
                poiDetails.put("y", this.y);
            }else{
                JSONObject poi = new JSONObject();
                poi.put("building", this.building);
                poi.put("floor", this.floors);
                poi.put("name", this.names);
                poi.put("roomNumber", this.roomnumber);
                poi.put("category", this.category);
                poi.put("description", this.description);
                poi.put("highlighted", false);
                poi.put("x", this.x);
                poi.put("y", this.y);
                jsonType.add(poi);
            }    
            try (FileWriter files = new FileWriter(file)) {
            //We can write any JSONArray or JSONObject instance to the file
            files.write(jsonFile.toJSONString()); 
            files.flush();
            } catch (IOException e) {
                e.printStackTrace();
            }
            this.setVisible(false);  
        } catch (FileNotFoundException ex) {
            Logger.getLogger(UserCreate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(UserCreate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(UserCreate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcActionPerformed
        // TODO add your handling code here:
        lower.setVisible(false);
        ground.setVisible(true);
        first.setVisible(true);
        second.setVisible(true);
        third.setVisible(true);
        fourth.setVisible(true);
        this.building = "MC";
    }//GEN-LAST:event_mcActionPerformed

    private void ecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecActionPerformed
        // TODO add your handling code here:
        lower.setVisible(false);
        ground.setVisible(false);
        first.setVisible(true);
        second.setVisible(true);
        third.setVisible(false);
        fourth.setVisible(false);
        this.building = "EC";
    }//GEN-LAST:event_ecActionPerformed

    private void ahbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ahbActionPerformed
        // TODO add your handling code here:
        lower.setVisible(true);
        ground.setVisible(false);
        first.setVisible(true);
        second.setVisible(false);
        third.setVisible(false);
        fourth.setVisible(false);
        this.building = "AHB";
    }//GEN-LAST:event_ahbActionPerformed

    private void lowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerActionPerformed
        // TODO add your handling code here:
        this.floors = "Lower Floor";
    }//GEN-LAST:event_lowerActionPerformed

    private void groundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groundActionPerformed
        // TODO add your handling code here:
        this.floors = "Ground Floor";
    }//GEN-LAST:event_groundActionPerformed

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        // TODO add your handling code here:
        this.floors = "First Floor";
    }//GEN-LAST:event_firstActionPerformed

    private void secondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondActionPerformed
        // TODO add your handling code here:
        this.floors = "Second Floor";
    }//GEN-LAST:event_secondActionPerformed

    private void thirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdActionPerformed
        // TODO add your handling code here:
        this.floors = "Third Floor";
    }//GEN-LAST:event_thirdActionPerformed

    private void fourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthActionPerformed
        // TODO add your handling code here:
        this.floors = "Fourth Floor";
    }//GEN-LAST:event_fourthActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ahb;
    private javax.swing.JTextField cat;
    private javax.swing.JTextField desc;
    private javax.swing.JButton ec;
    private javax.swing.JButton first;
    private javax.swing.JButton fourth;
    private javax.swing.JButton ground;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton lower;
    private javax.swing.JButton mc;
    private javax.swing.JTextField name;
    private javax.swing.JTextField rm;
    private javax.swing.JButton second;
    private javax.swing.JButton third;
    // End of variables declaration//GEN-END:variables
}
